config/routes.rb
Rails.application.routes.draw do
  get 'names/favorite'

  root 'home#index'
  
  resources :names do
    put :favorite, on: :member
  end

  get "/auth/:provider/callback" => "sessions#create"
  delete '/logout', to: 'sessions#destroy'

end

app/models/babyname.rb
class Babyname < ActiveRecord::Base
end

app/models/favorite_name.rb
class FavoriteName < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user
end

app/models/list.rb
class List < ActiveRecord::Base
end

app/models/name.rb
class Name < ActiveRecord::Base
  # Favorited by users
  has_many :favorite_names # just the 'relationships'
  has_many :favorited_by, through: :favorite_names, source: :user # the actual users favoriting a name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorite_names # just the 'relationships'
  has_many :favorites, through: :favorite_names, source: :name # the actual names a user favorites


  def self.find_or_create_from_omniauth(auth_hash)
    # Find or create a user
    #user = User.where(uid: auth_hash["uid"]).where(provider: auth_hash["provider"]).first
    user = self.find_by(uid: auth_hash["uid"], provider: auth_hash["provider"])
    # user = //something else here//
    if !user.nil?
    #   return user that was found
      return user
    else
    #   no user found, do something here
      user = User.new
      user.uid = auth_hash["uid"]
      user.provider = auth_hash["provider"]
      user.first_name = auth_hash["info"]["first_name"]
      user.last_name = auth_hash["info"]["last_name"]
      user.image = auth_hash["info"]["image"]
      user.url = auth_hash["info"]["urls"]["Facebook"]
      if user.save
        return user
      else
        return nil
      end
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/names_controller.rb
class NamesController < ApplicationController

  def index
    @names = Name.all
  end

  def new
    @name = Name.new
  end

  def create
    @name = Name.new(create_name_params[:name])
    if(@name.save)
      redirect_to name_path(@name.id)#redirect in case user tries to post another form - brings them to entered view
    else
      render :new
    end
  end

  def show
    @name = Name.find(params[:id])
  end

  def favorite
    # Add and remove favorite names
    # for current_user
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @name
      redirect_to :back, notice: '¡Añadiste el nombre #{@name.name} a tus favoritos!'

    elsif type == "unfavorite"
      current_user.favorites.delete(@name)
      redirect_to :back, notice: 'Eliminaste el nombre #{@name.name} de tus favoritos.'

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'No sucedió nada.'
    end

  end


  private
  def create_name_params
    params.permit(name: [:name, :gender, :origin, :meaning, :diminutives, :famous, :royalty, :interesting]) #double check attributes
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    #accepts OAuth information from Spotify, finds or creates a User account, and sets user_id in session
    auth_hash = request.env['omniauth.auth']   #request is a variable that you get
    @user = User.find_or_create_from_omniauth(auth_hash)
    # user = User.log_in(params[:xemail], params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    #deletes user_id from session
    session.delete :user_id
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def favorites
    @user_favorites = current_user.favorites
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if current_user %>
  <div class="page-header">
    <h1>Here is some info about you...</h1>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <ul>
        <li><strong>Nombre:</strong> <%= current_user.first_name %></li>
        <li><strong>Apellido:</strong> <%= current_user.last_name %></li>
        <li><strong>Provider:</strong> <%= current_user.provider %></li>
        <li><strong>uID:</strong> <%= current_user.uid %></li>
        <li><strong>Avatar URL:</strong> <%= current_user.image %></li>
        <li><strong>URL:</strong> <%= current_user.url %></li>
      </ul>
    </div>
  </div>
<% else %>
  Welcome!
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Namedatabase</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    <ul class="nav navbar-nav pull-right">
      <li><%= image_tag current_user.image, alt: current_user.first_name %></li>
      <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
    </ul>
  <% else %>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Facebook', '/auth/facebook' %></li>
    </ul>
  <% end %>


<%= yield %>

</body>
</html>

app/views/names/favorite.html.erb
<h1>Names#favorite</h1>
<p>Find me in app/views/names/favorite.html.erb</p>

app/views/names/index.html.erb
<h1> Lista de Nombres: </h1>

<%= link_to "Agregar Nombre", new_name_path %>

<% @names.each do |name| %>
  <%= link_to name.name, name_path(name.id) %>
<% end %>

app/views/names/new.html.erb
<h1>Agregar Nuevo Nombre</h1>

<%= form_for @name do |f| %>
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>

  <p><%= f.label :gender %>
  <%= f.text_field :gender %></p>

  <p><%= f.label :origin %>
  <%= f.text_field :origin %></p>

  <p><%= f.label :meaning %>
  <%= f.text_field :meaning %></p>

  <p><%= f.label :diminutives %>
  <%= f.text_area :diminutives %></p>

  <p><%= f.label :famous %>
  <%= f.text_area :famous %></p>

  <p><%= f.label :royalty %>
  <%= f.text_area :royalty %></p>

  <p><%= f.label :interesting %>
  <%= f.text_area :interesting %></p>

  <%= f.submit %>
  <% end %>

app/views/names/show.html.erb
<h2>El significado del nombre <%= @name.name %></h2>
<% if current_user %>
  <%= link_to "Añadir a Favoritos",   favorite_name_path(@name, type: "favorite"), method: :put %>
  <%= link_to "Eliminar de Favoritos", favorite_name_path(@name, type: "unfavorite"), method: :put %>
<% end %>

Nombre: <%= @name.name%>
Origen: <%= @name.origin%>
Género: <%= @name.gender%>
Significado: <%= @name.meaning%>
Nombres cortos: <%= @name.diminutives%>
Famosos: <%= @name.famous%>
Realeza: <%= @name.royalty%>
Datos interesantes: <%= @name.interesting%>